--- #YAML:1.0
name: Contentment
version: 0.009_018
author:
  - Andrew Sterling Hanenkamp E<lt>hanenkamp@users.sourceforge.netE<gt>
abstract: A Mason/Perl-based content management system
license: perl
generated_by: Module::Build version 0.261, without YAML.pm
