---
name: Contentment
version: 0.011_033
author:
  - Andrew Sterling Hanenkamp E<lt>hanenkamp@cpan.orgE<gt>
abstract: Contentment is a Perl-based web content management system
license: perl
requires:
  CGI: 0
  Cache::Cache: 0
  Carp: 0
  Class::Accessor: 0
  Class::Date: 0
  Class::Delegator: 0
  Class::Singleton: 0
  Class::WhiteHole: 0
  Cwd: 0
  Data::UUID: 0
  DateTime: 0
  Digest: 0
  Exception::Class: 1.22
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  File::System: 1.16
  HTML::TokeParser: 0
  HTTP::Request::Common: 0
  IO::Handle: 0
  IO::NestedCapture: 0
  LWP::UserAgent: 0
  List::MoreUtils: 0
  List::Util: 0
  MIME::Types: 0
  Oryx: 0.16
  Params::Validate: 0
  Pod::Simple: 0
  Readonly: 0
  Scalar::Util: 0
  Template: 2
  Test::Deep: 0
  Text::Balanced: 0
  URI: 0
  YAML: 0
recommends:
  Apache::Test: 1.25
  CGI::Fast: 0
  FCGI: 0
provides:
  Contentment:
    file: lib/Contentment.pm
    version: 0.011_033
  Contentment::Context:
    file: lib/Contentment/Context.pm
    version: 0.011_033
  Contentment::Exception:
    file: lib/Contentment/Exception.pm
    version: 0.011028
  Contentment::Generator:
    file: lib/Contentment/Generator.pm
    version: 0.011_033
  Contentment::Hooks:
    file: lib/Contentment/Hooks.pm
    version: 0.03
  Contentment::Hooks::Iterator:
    file: lib/Contentment/Hooks.pm
    version: 0.03
  Contentment::Log:
    file: lib/Contentment/Log.pm
    version: 0.011_033
  Contentment::MIMETypes:
    file: lib/Contentment/MIMETypes.pm
    version: 0.011_033
  Contentment::Request:
    file: lib/Contentment/Request.pm
    version: 0.011_033
  Contentment::Response:
    file: lib/Contentment/Response.pm
    version: 0.011_033
  Contentment::Test:
    file: lib/Contentment/Test.pm
    version: 0.011_033
generated_by: Module::Build version 0.2611
